Dequeue Google Fonts
mailoptin/core pull request #19
Opened 2020-08-15 11:09 UTC by ShoboySnr

This PR dequeue Google fonts

2020-08-17 06:25 UTC, ShoboySnr commented
Okay

2020-08-17 09:24 UTC, ShoboySnr commented
I have pushed @w3guy please check

2020-08-17 17:12 UTC, w3guy commented
@ShoboySnr great job. Did you actually test and confirmed it works as expected?

2020-08-17 17:23 UTC, ShoboySnr commented
Yes i did. When the dequeue  check box is checked, it removes the Google googleapis script and that Webfont function script.

2020-08-19 09:16 UTC, w3guy requested changes

2020-08-19 09:16 UTC, w3guy commented on src/Admin/SettingsPage/Settings.php
> +                            'label'       => __('Dequeue Google Fonts', 'mailoptin'),
@ShoboySnr please change to 
```suggestion
                            'label'       => __('Disable Google Fonts', 'mailoptin'),
```

2020-08-19 09:16 UTC, w3guy commented on src/Admin/SettingsPage/Settings.php
> +                            'checkbox_label' => __('Dequeue', 'mailoptin')
And this too.

```suggestion
                            'checkbox_label' => __('Disable', 'mailoptin')
```

2020-08-19 11:22 UTC, merged