Fix Google Font Dequeue Bug
mailoptin/core pull request #20
Opened 2020-09-02 06:36 UTC by ShoboySnr

Please find the PR to fix the google fonts bug

2020-09-02 19:36 UTC, w3guy requested changes

2020-09-02 19:36 UTC, w3guy commented on src/RegisterScripts.php
Where is the similar fix for webfont_loader_js_script() in Core/src/OptinForms/AbstractOptinForm.php ?

2020-09-03 04:36 UTC, w3guy commented
@ShoboySnr your dequeue check looks hacky to me. I cleaned it up but I didn't test.

Please pull in my changes, test thoroughly on your system if dequeue works.

2020-09-03 04:37 UTC, ShoboySnr commented
Okay @w3guy

2020-09-05 16:27 UTC, merged